name: Build wheels

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get all history for proper version detection

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Use Python 3.11+ for cibuildwheel 3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel

      - name: Build Rust binary (Unix)
        if: runner.os != 'Windows'
        run: |
          cargo build --release --package ruff_api_analyzer
          mkdir -p crates/ruff_api_analyzer/python/pubscan/bin
          cp target/release/api-analyzer crates/ruff_api_analyzer/python/pubscan/bin/
          ls -la crates/ruff_api_analyzer/python/pubscan/bin/
      
      - name: Build Rust binary (Windows)
        if: runner.os == 'Windows'
        run: |
          cargo build --release --package ruff_api_analyzer
          mkdir -Force -Path crates/ruff_api_analyzer/python/pubscan/bin
          Copy-Item -Path "target\release\api-analyzer.exe" -Destination "crates\ruff_api_analyzer\python\pubscan\bin\"
          Get-ChildItem -Path "crates\ruff_api_analyzer\python\pubscan\bin\"

      - name: Create binary marker file to force platform wheel
        run: |
          cd crates/ruff_api_analyzer/python
          # Create an __init__.py file in the bin directory
          echo "# This directory contains platform-specific binaries" > pubscan/bin/__init__.py
          # Create a MANIFEST.in file to ensure binary files are included
          echo "include pubscan/bin/*" > MANIFEST.in
          # Create a .dist-info/WHEEL file marker to force platform specificity
          mkdir -p .dist-info
          echo "[bdist_wheel]" > .dist-info/WHEEL
          echo "py-api-version=1.0" >> .dist-info/WHEEL
          echo "platform=true" >> .dist-info/WHEEL

      - name: Build wheels
        env:
          # Force cibuildwheel to treat wheels as platform-specific
          CIBW_REPAIR_WHEEL_COMMAND: ""
          CIBW_BEFORE_BUILD: "pip install -e ."
          CIBW_ENVIRONMENT: "CIBUILDWHEEL=1 FORCE_BDIST_WHEEL_PLATFORM=1"
          CIBW_SKIP: "pp* *-musllinux*"
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-* cp313-*"
        run: |
          cd crates/ruff_api_analyzer/python
          # Check if the binary exists before building
          python -c "import os, sys; bin_exists = os.path.exists('pubscan/bin/api-analyzer') or os.path.exists('pubscan/bin/api-analyzer.exe'); print(f'Binary exists: {bin_exists}'); sys.exit(0 if bin_exists else 1)"
          # Make sure plat_name is set to True in the options
          python -c "import sys; f = open('setup.py', 'r'); content = f.read(); f.close(); if 'plat_name' not in content: f = open('setup.py', 'w'); f.write(content.replace('options={\\\"bdist_wheel\\\": {\\\"py_limited_api\\\": False, \\\"universal\\\": False}}', 'options={\\\"bdist_wheel\\\": {\\\"py_limited_api\\\": False, \\\"universal\\\": False, \\\"plat_name\\\": True}}')); f.close(); print('Updated setup.py')"
          # Build wheels with cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse --debug

      - name: Check wheel contents 
        run: |
          cd crates/ruff_api_analyzer/python
          python -m pip install wheel
          ls -la wheelhouse/
          for wheel in wheelhouse/*.whl; do
            echo "Inspecting $wheel"
            python -c "import zipfile; f = zipfile.ZipFile('$wheel'); print('\n'.join(f.namelist()))" | grep -i bin || echo "No bin directory found in wheel"
          done

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: crates/ruff_api_analyzer/python/wheelhouse/*.whl

  upload_pypi:
    name: Upload to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    # Only release to PyPI on tag pushes
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Prepare distribution files
        run: |
          mkdir -p dist_upload
          find dist -name "*.whl" -exec cp {} dist_upload \;
          ls -la dist_upload/

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist_upload/
