name: Build wheels

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Remove Windows for now
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel

      - name: Build wheels
        # Run cibuildwheel from the directory containing pyproject.toml
        working-directory: crates/ruff_api_analyzer/python
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          # Build for Python 3.10 - 3.13
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"
          # Install Rust inside the cibuildwheel environment using rustup
          CIBW_BEFORE_BUILD: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y"
          # Add Cargo bin to PATH using CIBW_ENVIRONMENT for earlier access
          # Note: Path separators differ; GITHUB_WORKSPACE might be needed if $HOME isn't reliable
          CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH"'
          # No repair command needed, maturin handles tags
          CIBW_REPAIR_WHEEL_COMMAND: ""

      - name: Install and Test Wheel
        # Test in a different directory to ensure it works standalone
        run: |
          # Create a temporary directory for testing
          mkdir ../test_install
          cd ../test_install
          # Install one of the built wheels
          python -m pip install --find-links=../python/wheelhouse pubscan
          # Test the installed binary
          api-analyzer --help
        working-directory: crates/ruff_api_analyzer

      - name: Check wheel contents
        # Check relative to where wheels were built
        working-directory: crates/ruff_api_analyzer/python
        run: |
          python -m pip install wheel
          python -c "import glob, zipfile; wheels = glob.glob('wheelhouse/*.whl'); print(f'Found wheels: {wheels}'); [print(f'Contents of {w}: {sorted(zipfile.ZipFile(w).namelist())}\n') for w in wheels]"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          # Path relative to workspace root
          path: crates/ruff_api_analyzer/wheelhouse/*.whl

  upload_to_pypi:
    name: Upload to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    # Only run on tags
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
